Fix/gopls 1.1x support
sublimelsp/LSP-gopls pull request #10
Opened 2021-10-31 20:53 UTC by TheSecEng

**What**

Fixes support for Golang versions 1.15 and below.

**Note**
Gopls only supports the last 2 versions of go and attempts to prevent breaking changes for the last 4 versions

2021-10-31 21:02 UTC, TheSecEng commented
This how now been tested on:

Windows: Golang 1.16
Windows: Golang 1.15
MacOS: Golang 1.16
MacOS: Golang 1.15

2021-10-31 21:02 UTC, TheSecEng commented
Fixes #9

2021-10-31 21:11 UTC, ofen commented on plugin.py
> +def run_go_command(go: str, sub_command: str = 'install', url: Any[str, None] = None, env_vars: dict = {}) -> Tuple[str, str, int]:
Dict as default is mutable and stored inside function (could lead to "unexpected side-effects")

2021-10-31 21:21 UTC, rwols commented on plugin.py
> +        env_vars['GOCACHE'] = os.path.join(cls.basedir(), 'go-build')
shouldn't this also set `GOTMPDIR` or was this not necessary after all? Is it now still installing in C:\Windows ?

2021-10-31 21:45 UTC, TheSecEng commented
@ofen if you could test before we merge and cut a release that would be awesome. As you are running 1.13 which is the last version gopls will possible support

2021-10-31 22:27 UTC, rchl requested changes

2021-10-31 22:27 UTC, rchl commented on plugin.py
> +RE_VER = re.compile(r"go(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)")
What's the logic behind this strange regex?

why not just:
```suggestion
RE_VER = re.compile(r"go(\d+)\.(\d+)\.(\d+)")
```
?

2021-10-31 22:27 UTC, rchl commented on plugin.py
> +        go_binary = str(which('go'))
Why repeating this instead of just making it a part of `run_go_command`?

2021-10-31 22:27 UTC, rchl commented on plugin.py
> +                'go version error', stderr, 'returncode', return_code)
(nit) You have lines up to 120th column and yet sometimes go for a line break in short lines like this one. Not sure why. :)

2021-10-31 22:27 UTC, rchl commented on plugin.py
> +        go_sub_command = 'get' if go_version[1] < 16 else 'install'
Shouldn't this also compare the major component? If major is bumped up at some point, this will still keep applying this logic.

2021-11-01 06:27 UTC, jingyuexing commented
```
Traceback (most recent call last):
  File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 354, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 252, in create_transport
    process = start_subprocess()
  File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 241, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 323, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system can not find the file specified。

SublimeLinter: WARNING: golangcilint output:
level=error msg="Running error: context loading failed: no go files to analyze"

WARNING:SublimeLinter.plugin.golangcilint:golangcilint output:
level=error msg="Running error: context loading failed: no go files to analyze"
```

2021-11-01 06:46 UTC, jingyuexing commented
> subprocess

go version is : go version go1.15 windows/amd64

2021-11-01 06:46 UTC, jingyuexing commented
> ```
> Traceback (most recent call last):
>   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 354, in start_async
>     transport = create_transport(transport_config, transport_cwd, session)
>   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 252, in create_transport
>     process = start_subprocess()
>   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 241, in start_subprocess
>     return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
>   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 323, in _start_subprocess
>     cwd=cwd)
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1110, in _execute_child
> FileNotFoundError: [WinError 2] The system can not find the file specified。
> 
> SublimeLinter: WARNING: golangcilint output:
> level=error msg="Running error: context loading failed: no go files to analyze"
> 
> WARNING:SublimeLinter.plugin.golangcilint:golangcilint output:
> level=error msg="Running error: context loading failed: no go files to analyze"
> ```

go version go1.15 windows/amd64

2021-11-01 09:27 UTC, ofen commented
@TheSecEng Hi! Commit abb9f616f0fab48047d190fda97c1deef46f989a works on Ubuntu 20.04.2 LTS, Sublime Text 4 Build 4113, go1.13.8 (https://github.com/sublimelsp/LSP-gopls/issues/9#issuecomment-955673875). I tested auto-completion, format-on-safe and some minor things like jump-to-definition and LGTM. There is also new exception in console after each plugin reload that could be bug (?).

```
reloading python 3.3 plugin LSP-gopls.plugin
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 540, in _update_panel_main_thread
    panel.run_command("lsp_update_panel", {"characters": characters})
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1312, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1490, in run_
    self.view.end_edit(edit)
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1273, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 924, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "/home/user/.config/sublime-text-3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1020, in __getitem__
    raise IndexError()
IndexError
reloading python 3.3 plugin LSP-gopls.plugin
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 540, in _update_panel_main_thread
    panel.run_command("lsp_update_panel", {"characters": characters})
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1312, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1490, in run_
    self.view.end_edit(edit)
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1273, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 924, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "/home/user/.config/sublime-text-3/Installed Packages/AutoFileName.sublime-package/autofilename.py", line 162, in on_modified
    sel = view.sel()[0].a
  File "/opt/sublime_text/Lib/python33/sublime.py", line 1020, in __getitem__
    raise IndexError()
IndexError

```

2021-11-01 09:44 UTC, rchl commented
@ofen that's a bug in `AutoFileName`. It should not assume that there is always a selection in the view.

2021-11-01 16:20 UTC, TheSecEng commented on plugin.py
> +        go_binary = str(which('go'))
Leaves room for if there is every other breaking changes that we need to compare versions with

2021-11-01 16:21 UTC, TheSecEng commented on plugin.py
> +        go_binary = str(which('go'))
Ahh the which go. I have fixed that

2021-11-01 16:23 UTC, TheSecEng commented
> > ```
> > Traceback (most recent call last):
> >   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 354, in start_async
> >     transport = create_transport(transport_config, transport_cwd, session)
> >   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 252, in create_transport
> >     process = start_subprocess()
> >   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 241, in start_subprocess
> >     return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
> >   File "E:\Programming\sublime_text_4100\Data\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 323, in _start_subprocess
> >     cwd=cwd)
> >   File "./python3.3/subprocess.py", line 819, in __init__
> >   File "./python3.3/subprocess.py", line 1110, in _execute_child
> > FileNotFoundError: [WinError 2] The system can not find the file specified。
> > 
> > SublimeLinter: WARNING: golangcilint output:
> > level=error msg="Running error: context loading failed: no go files to analyze"
> > 
> > WARNING:SublimeLinter.plugin.golangcilint:golangcilint output:
> > level=error msg="Running error: context loading failed: no go files to analyze"
> > ```
> 
> 
> go version go1.15 windows/amd64

This seems line an issue with LSP? IDK there is nothing in this error that I can interpret. But the LSP devs should be able to tell?

2021-11-01 16:30 UTC, rchl commented
> > > FileNotFoundError: [WinError 2] The system can not find the file specified。
> 
> This seems line an issue with LSP? IDK there is nothing in this error that I can interpret. But the LSP devs should be able to tell?

It means that the constructed `command` contains path that doesn't exist.

2021-11-01 17:45 UTC, TheSecEng commented
@jingyuexing can you confirm that the gopls binary was actually installed into the `${storage_path}/LSP-gopls/bin/` folder

2021-11-01 18:01 UTC, rwols commented on plugin.py
> +    if sublime.platform() == 'Windows':
Shouldn’t this be lowercase `windows` instead of `Windows`?

2021-11-01 18:04 UTC, rwols commented on plugin.py
> +            'get' if (go_version[0] <= 1 and go_version[1] < 16) else 'install'
`'get' if go_version < (1, 16, 0) else 'install'`

2021-11-01 18:06 UTC, rwols commented on plugin.py
> +    go_binary = str(which('go'))
I feel like these `which` calls are redundant because Popen already resolves the binary if it’s not an absolute path?

2021-11-01 18:07 UTC, rwols commented on plugin.py
> +def to_int(value: Optional[str] = '') -> int:
Why have a default value here? What’s the point of calling `to_int()` without arguments?

2021-11-01 18:07 UTC, TheSecEng commented on plugin.py
> +    go_binary = str(which('go'))
I thought I tested this and it didn't work. Let me test locally real quick.

2021-11-01 18:08 UTC, TheSecEng commented on plugin.py
> +    go_binary = str(which('go'))
You are right

2021-11-01 19:03 UTC, jingyuexing commented
> @jingyuexing can you confirm that the gopls binary was actually installed into the `${storage_path}/LSP-gopls/bin/` folder

yes,i'm sure,I even installed it manually

2021-11-01 19:20 UTC, rchl approved these changes
Haven't tested but it looks good. (just some minor nits)

2021-11-01 19:20 UTC, rchl commented on plugin.py
> +    )
(nit) casting to string is not needed

2021-11-01 19:20 UTC, rchl commented on plugin.py
> +            env_vars = {}
This doesn't seem needed or even wanted. Passing `None` will inherit variables from the current environment which is more appropriate than having no variables since most things would fail to execute then.

2021-11-01 19:20 UTC, rchl commented on plugin.py
> +        )
that's a weird formatting

2021-11-01 19:21 UTC, rchl commented
> yes,i'm sure,I even installed it manually

it looks like it should work better with latest changes?

2021-11-01 19:22 UTC, jingyuexing commented
> Haven't tested but it looks good. (just some minor nits)

😂😂

2021-11-01 19:24 UTC, jingyuexing commented
> > yes,i'm sure,I even installed it manually
> 
> it looks like it should work better with latest changes?

i'm haven't test it

2021-11-01 22:58 UTC, jingyuexing commented
> > yes,i'm sure,I even installed it manually
> 
> it looks like it should work better with latest changes?

The same error message as before, "File not found"

2021-11-01 23:02 UTC, jingyuexing commented
> > yes,i'm sure,I even installed it manually
> 
> it looks like it should work better with latest changes?

if using the default config from LSP, working fine, but `LSP-gopls` will report information:"can't find the file"

2021-11-01 23:11 UTC, jingyuexing commented
![image](https://user-images.githubusercontent.com/19589872/139753534-fad4ccf1-3f08-41cf-979a-7f77134565f7.png)

```
LSP: starting ['E:\\Programming\\sublime_text_4100\\Data\\Package Storage/LSP-gopls/gopls'] in I:\Code\go\Study_GO
Unable to start subprocess for gopls
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system can not find the file specified。
```
look like is directory wrong: `Package Storage/LSP-gopls/gopls` ,but the real path is `Package Storage/LSP-gopls/bin/gopls`

2021-11-01 23:14 UTC, jingyuexing commented
**LSP: starting ['E:\\Programming\\sublime_text_4100\\Data\\Package Storage/LSP-gopls/gopls']**

2021-11-01 23:17 UTC, jingyuexing commented
> **LSP: starting ['E:\Programming\sublime_text_4100\Data\Package Storage/LSP-gopls/gopls']**

I moved the file to the `Package Storage/LSP-gopls` directory, everything is normal

2021-11-01 23:19 UTC, jingyuexing commented
> > **LSP: starting ['E:\Programming\sublime_text_4100\Data\Package Storage/LSP-gopls/gopls']**
> 
> I moved the file to the `Package Storage/LSP-gopls` directory, everything is normal

![image](https://user-images.githubusercontent.com/19589872/139754461-49a6ad05-8af1-493e-b895-e8ce0830e12d.png)

2021-11-01 23:19 UTC, TheSecEng commented
What are your LSP-settings?

Zach Schulze
On Nov 1, 2021, 4:17 PM -0700, jingyuexing ***@***.***>, wrote:
> > LSP: starting ['E:\Programming\sublime_text_4100\Data\Package Storage/LSP-gopls/gopls']
> I moved the file to the Package Storage/LSP-gopls directory, everything is normal
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-01 23:21 UTC, jingyuexing commented
> What are your LSP-settings? Zach Schulze
> […](#)
> On Nov 1, 2021, 4:17 PM -0700, jingyuexing ***@***.***>, wrote: > LSP: starting ['E:\Programming\sublime_text_4100\Data\Package Storage/LSP-gopls/gopls'] I moved the file to the Package Storage/LSP-gopls directory, everything is normal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
My custom config is：
```
"gopls": {
            "enabled": false
 },
```
The default config is:
```
"gopls": {
      "command": [
        "gopls"
      ],
      "selector": "source.go",
    },
```

2021-11-01 23:52 UTC, rwols approved these changes

2021-11-02 00:16 UTC, TheSecEng commented
> > What are your LSP-settings? Zach Schulze
> > […](#)
> > On Nov 1, 2021, 4:17 PM -0700, jingyuexing _**@**_.***>, wrote: > LSP: starting ['E:\Programming\sublime_text_4100\Data\Package Storage/LSP-gopls/gopls'] I moved the file to the Package Storage/LSP-gopls directory, everything is normal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> My custom config is：
> 
> ```
> "gopls": {
>             "enabled": false
>  },
> ```
> 
> The default config is:
> 
> ```
> "gopls": {
>       "command": [
>         "gopls"
>       ],
>       "selector": "source.go",
>     },
> ```

Your default config is wrong. 

It should be 
```
  "command": [
    "${storage_path}/LSP-gopls/bin/gopls"
  ],
  ```

2021-11-02 00:16 UTC, merged