fix problems under Windows
sublimelsp/LSP-gopls pull request #12
Opened 2021-11-10 10:26 UTC by wsw0108

also, run `go get/install` with cwd=tempdir to avoid modify opened go project's go.mod

2021-11-11 20:23 UTC, TheSecEng commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
This is not required. `${storage_path}` is automatically resolved by LSP.

2021-11-11 20:34 UTC, TheSecEng requested changes
Please review the comments

2021-11-11 20:34 UTC, TheSecEng commented on plugin.py
> +            'command', [os.path.join(cls.basedir(), 'bin', binary)]
This shouldn't be required either. As we don't need to do the replacement

2021-11-11 20:34 UTC, TheSecEng commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
This isn't required as this is handled by pythons `shutil.which` command. Binaries can be provided without `.exe` and it will locate them still

2021-11-11 20:34 UTC, TheSecEng commented on plugin.py
> +    return settings.get(key, default)
Good fix. Thanks

2021-11-11 20:34 UTC, TheSecEng commented on plugin.py
> +            cwd=tempdir,
Has this been tested on all platforms?

2021-11-11 20:35 UTC, TheSecEng commented
Thanks for the PR. Can you please review the comments / changes requested

2021-11-11 21:01 UTC, rchl commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
The path is being passed to `which` which won't understand that variable.

Because of the change in `def get_setting`, this now actually gets the `command` from the settings rather than falling back to the default value.

So I can see why it's done like that but that doesn't mean I like it. :)

2021-11-11 21:08 UTC, rchl commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
That said, I don't really see a better solution without making some core changes to the plugin API.

2021-11-11 21:20 UTC, TheSecEng commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
LSP can just create a wrapper around `which` to do binary detection. I see what you mean now, I don't really like this either. Will think on it

2021-11-11 21:26 UTC, rchl commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
Proper solution would need to take into account the variables from the current Window and also `additional_variables` provided by the AbstractPlugin class. So it can't be just free-function like that.

The only thing that comes to mind is exposing a new API that provides more information in the passed arguments like a config with fully resolved command (or at least fully resolved command). But something like that would require more work and designing.

2021-11-11 22:49 UTC, wsw0108 commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
if we pass full path instead of just command name, then the suffix are needed.

2021-11-11 22:54 UTC, wsw0108 commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
i dont like this replace thing too.
so it seems like we should wait changes from upstream.

2021-11-11 22:56 UTC, wsw0108 commented on plugin.py
> +            cwd=tempdir,
not yet. i can only test on windows and linux.

2021-11-12 07:53 UTC, rchl commented on plugin.py
> +        gopls_binary = command[0].replace('${storage_path}', cls.storage_path())
I don't think you should wait unless you plan to do the upstream changes yourself.

2021-11-12 08:28 UTC, wsw0108 commented on plugin.py
> +            cwd=tempdir,
After open a go project from either `subl .` or desktop entry, `os.getcwd()` in sublime console return `/opt/sublime_text`.
So under Linux, `cwd=tempdir` is not neccessary.

2021-11-12 08:30 UTC, rchl commented on plugin.py
> +            cwd=tempdir,
Doesn't it make sense to set consistent working directory for all platforms?
Doesn't seem right to write something to `/opt/sublime_text`, whatever that directory is.

2021-11-12 09:27 UTC, wsw0108 commented on plugin.py
> +            cwd=tempdir,
since `go get/install` does not write other things then may modify 'go.mod', so the cwd actually does not matter.

2021-11-12 12:59 UTC, wsw0108 commented on plugin.py
> +            'command', [os.path.join(cls.basedir(), 'bin', binary)]
This is required by `shutil.which` with full path.

2021-11-14 06:06 UTC, TheSecEng commented
@rchl I would like to let you make the call, should we implement this or wait for changes on LSP? Looking for your approval

2021-11-14 11:04 UTC, rchl commented
I'm good with those changes for now.

2021-11-14 11:12 UTC, rchl requested changes

2021-11-14 11:12 UTC, rchl commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
I'm surprised that this is needed for the check done by `_is_gopls_installed` but it's not necessary to actually modify the `command` in the ClientConfig? Can you explain that?

2021-11-14 12:32 UTC, wsw0108 commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
Because of below:
```
reloading settings Packages/User/Preferences.sublime-settings
>>> shutil.which("C:/Go/bin/go.exe")
'C:/Go/bin/go.exe'
>>> shutil.which("C:/Go/bin/go")
>>> shutil.which("C:/Go/bin/go.exe")
'C:/Go/bin/go.exe'
```

`shutil.which` needs `.exe` for fullpath. 

When run as program, `C:/Go/bin/go` and `C:/Go/bin/go.exe` both works.

2021-11-14 13:05 UTC, rchl commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
There is no point in calling `shutil.which` on a full path. You can just check if the path exists instead. `which` is used to locate path of binaries in the PATH. So like this:

```
Python 3.3>>> shutil.which('go')
'C:\\Program Files\\Go\\bin\\go.EXE'
```

Now, I've tested on Windows and for me things work without your fixes even. So I'm not quite sure what is happening on your system.

2021-11-14 13:15 UTC, rchl commented on plugin.py
> +            gopls_binary = gopls_binary + '.exe'
OK, I see now. The fix for reading the settings makes it so that gopls is re-installed on every start. It wasn't clear from your PR that that's what you are fixing.

2021-11-14 13:26 UTC, rchl approved these changes
Looks good after all. :)

2022-01-30 03:38 UTC, merged