update gopls v0.7.5
sublimelsp/LSP-gopls pull request #14
Opened 2022-02-25 23:30 UTC by TheSecEng

2022-03-11 17:52 UTC, rchl commented on LSP-gopls.sublime-settings
> +  "settings": {}
Why did you decide to remove all default settings from here? It's unlike any other packages.
And while you can argue that people should be using LSP-json, it's still much more convenient to have the list of setting available to see at once rather than have to go through each completion and fetch documentation for each.

2022-03-11 19:32 UTC, TheSecEng commented on LSP-gopls.sublime-settings
> +  "settings": {}
Mainly because I figured LSP-json is just implied. But good point on those not using it. I will revert this change

2022-03-24 08:12 UTC, rchl requested changes

2022-03-24 08:12 UTC, rchl commented on LSP-gopls.sublime-settings
> +    "experimentalUseInvalidMetadata": false,
Missing `gopls.` prefix and doesn't match the schema.

2022-03-24 08:12 UTC, rchl commented on sublime-package.json
> +                    "gopls.experimentalUseInvalidMetadata": {
Please add:

```
"additionalProperties": false,
```

It will catch issues when someone uses unsupported setting.

2022-03-24 21:07 UTC, rchl approved these changes

2022-03-24 22:56 UTC, merged